apiVersion: v1
kind: Service
metadata:
  name: molecule-service
  labels:
    app: molecule
spec:
  selector:
    app: molecule
  type: NodePort
  ports:
  - protocol: TCP
    port: 443
    targetPort: 9090
